mysite/food/urls.py
from . import views
from django.urls import path
app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('<int:pk>',views.FoodDetail.as_view(),name='detail'),

    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('pdf/',include('pdf.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('profile/',user_views.userprofile,name='profile'),
  
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/pdf/urls.py
from django.urls import path
from pdf import views
app_name='pdf'
urlpatterns = [  
    path('',views.accept,name="accept"),
    path('<int:id>/',views.resume,name="resume"),
    path('list/',views.list,name="list"),
    
    ]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_desc = models.CharField(max_length=200)
    item_image = models.CharField(max_length=1000,default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg")

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={'pk':self.pk})

mysite/pdf/models.py
from django.db import models
 
# Create your models here.
class Profile(models.Model):
 
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    summary = models.TextField(max_length=2000)
    degree = models.CharField(max_length=200)
    school = models.CharField(max_length=200)
    university = models.CharField(max_length=200)
    previous_work = models.TextField(max_length=1000)
    skills = models.TextField(max_length=1000)
 

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_picture')
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email =  forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

mysite/food/views.py
from django.shortcuts import render,redirect
from food.models import Item
from .forms import ItemForm
from  django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexClassView(LoginRequiredMixin,ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

class FoodDetail(LoginRequiredMixin,DetailView):
    model = Item
    template_name = 'food/detail.html'


# class based create view

class CreateItem(LoginRequiredMixin,CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/form-add.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
@login_required()
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/form-add.html',{'form':form,'item':item})
@login_required()
def delete_item(request,id):
    item = Item.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    return render(request,'food/delete-item.html',{'item':item})

mysite/pdf/views.py
from django.shortcuts import render,redirect
from .models import Profile
import pdfkit
from django.http import HttpResponse
from django.template import loader
import io
# Create your views here.
 
 
def accept(request):
    if request.method == "POST":
        name = request.POST.get("name","")
        email = request.POST.get("email","")
        phone = request.POST.get("phone","")
        summary = request.POST.get("summary","")
        degree = request.POST.get("degree","")
        school = request.POST.get("school","")
        university = request.POST.get("university","")
        previous_work= request.POST.get("previous_work","")
        skills = request.POST.get("skills","")
 
        profile = Profile(name=name,email=email,phone=phone,summary=summary,degree=degree,school=school,university=university,previous_work=previous_work,skills=skills)
        profile.save()
        return redirect('pdf:list')
 
    
    return render(request,'pdf/accept.html')
 
def resume(request,id):
    user_profile = Profile.objects.get(pk=id)
    template = loader.get_template('pdf/resume.html')
    html = template.render({'user_profile':user_profile})
    options ={
        'page-size':'Letter',
        'encoding':"UTF-8",
    }
    config = pdfkit.configuration(wkhtmltopdf=r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe")
    pdf = pdfkit.from_string(html,False,options,configuration=config)
    response = HttpResponse(pdf,content_type='application/pdf')
    response['Content-Disposition'] ='attachment'
    filename = "resume.pdf"
    return response
 
def list(request):
    profiles = Profile.objects.all()
    return render(request,'pdf/list.html',{'profiles':profiles})

mysite/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from users.forms import RegisterForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username},Your Account has been created')
            return redirect('login')
    else:
        form = RegisterForm
    return render(request,'users/register.html',{'form':form})
@login_required
def userprofile(request):
    return render(request,'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'food/style.css'%}">
    <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark"> 
        <a href="#" class="navbar-brand">FoodApp/PDF Generator</a>

        <div class="navbar">

            {% if user.is_authenticated%}
            <a class="nav-item nav-link" href="{% url 'food:index'%}">Home</a>
            <a class="nav-item nav-link" href="{% url 'pdf:accept'%}">CV Generator(PDF)</a>
            <a class="nav-item nav-link" href="{% url 'pdf:list'%}">Availale CV Generator</a>
            <a class="nav-item nav-link" href="{% url 'food:create_item'%}">Add Item</a>
            <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
            <a class="nav-item nav-link" href="{% url 'profile'%}">Profile</a>

            {% else %}
            <a class="nav-item nav-link" href="{% url 'register'%}">Register</a>
            <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
            {% endif %}




        </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}}">{{message}}</div>
      {% endfor %}
    {% endif %}
     {% block body %}
     {% endblock %}
</body>

</html>

mysite/food/templates/food/delete-item.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Delete {{item}}</title>
</head>
<body>
{% block body %}
<form method="POST">
    {%csrf_token%}
    <p>Aro you sure you want to delete "{{item}}"? </p>
    <div class="row">
        <div class="col-md-4">
            <button type="submit" class="btn btn-info"> Confirm </button>
        </div>
         <div class="col-md-4">
            <a href="{% url 'food:detail' item.id%}" class="btn btn-info"> Cancel </a>
        </div>

    </div>

</form>
{%endblock%}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Item Details</title>
</head>
<body>
        {% block body %}
    <h1> {{object.item_name}} Details</h1>
    <div class="container">
        <div class="col-md-6"> 
            <img src="{{object.item_image}}" height="200px" class="card" />


        </div>

        <div class="col-md-6"> 
            
            <h3>Item Name : {{object.item_name}}</h3>
            <h3>Item Price : Rs.{{object.item_price}}</h3>
            <h3>Item Description : {{object.item_desc}}</h3>

            <br />
            <div class="row" >
                <div class="col-md-4">
                    <a href="{% url 'food:update_item' object.id%}" class="btn btn-success"> Update </a>
                </div>
                  <div class="col-md-4">
                    <a href="{% url 'food:delete_item' object.id%}" class="btn btn-danger"> Delete </a>
                </div>
                 <div class="col-md-4">
                    <a href="{% url 'food:index'%}" class="btn btn-info"> Back </a>
                </div>
                </div>

            </div>




        </div>

    </div>


     {% endblock %}
</body>
</html>

mysite/food/templates/food/form-add.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Item</title>
</head>
<body>
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
              <form method="POST">
              {%csrf_token%}
                  {%for field in form%}
                  <div class="form-group">
                      {{field.name}} <br>
                      {{field}}
                  </div>
                  {%endfor%}
              <button type="submit" class="btn-info">Save Item </button>
              </form>
            </div>
        </div>
    </div>
</div>




 {% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    {% block body %}

    {% for item in item_list %}
    <div class="row">
        <div class='col-md-3 offset-md-2'>
            <img class="card" height="150px" src="{{item.item_image}}" />
        </div>

        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>Rs.{{item.item_price}}</h6>
            <h6>Posted By: {{ item.user_name }}</h6>
        </div>

        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>

    </div>

    {% endfor %}

    {% endblock %}
</body>
</html>

mysite/pdf/templates/pdf/accept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>CV Generator</title>
</head>
<body>
    {% extends 'food/base.html'%}
    {% block body %}
    <div class="container">
      <div class="row m-5">
        <div class="col-md-12">
          <h1>CV Generator</h1>
          <hr>
        </div>
      </div>
      <div class="row m-5">
        <div class="col-md-12">
          <h4>Please fill out your details</h4>
          
        </div>
      </div>
        <div class="row m-5">
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="">Name</label>
                      <input placeholder="Eg John Doe" type="text" class="form-control" id="name" name="name">
                    </div>
            
                    <div class="form-group">
                        <label for="">Email</label>
                        <input placeholder="Eg demo@gmail.com" type="text" class="form-control" id="email" name="email">
                      </div>
            
                      <div class="form-group">
                        <label for="">Phone</label>
                        <input placeholder="Eg 9999999999" type="text" class="form-control" id="phone" name="phone">
                      </div>
            
                      <div class="form-group">
                        <label for="">About You</label>
                        <textarea placeholder="Write something about you" type="text" class="form-control" id="summary" name="summary"></textarea>
                      </div>
                    
                      <div class="form-group">
                        <label for="">Degree</label>
                        <input placeholder="B-Tech Information Technology" type="text" class="form-control" id="degree" name="degree">
                      </div>
            
                      <div class="form-group">
                        <label for="">School</label>
                        <input placeholder="MIT" type="text" class="form-control" id="school" name="school">
                      </div>
            
            
                      <div class="form-group">
                        <label for="">University</label>
                        <input placeholder="MIT" type="text" class="form-control" id="university" name="university">
                      </div>
            
                      <div class="form-group">
                        <label for="">Previous Work</label>
                        <textarea placeholder="Programmer @ XYZ" type="text" class="form-control" id="previous_work" name="previous_work"></textarea>
                      </div>
            
                      <div class="form-group">
                        <label for="">Skills</label>
                        <textarea placeholder="eg C, C++, Python" type="text" class="form-control" id="skills" name="skills"></textarea>
                      </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
        </div>
    </div>

    {% endblock %}
</body>
</html>

mysite/pdf/templates/pdf/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 
    <title>CV List</title>
</head>
<body>
    {% extends 'food/base.html' %}
    {% block body %}
    <div class="container">
        <div class="row m-5">
            <div class="col-md-12">
                <h2>CV DATABASE CV LIST</h2>
            </div>

        </div>
        {% for profile in profiles %}
        <div class="row">
            <div class="col-md-6">
                {{profile.name}}
            </div>

            <div class="col-md-6">
               <a href="{% url 'pdf:resume' profile.id %}" class="btn btn-warning">Download CV</a>
            </div>
        </div>  
        <hr>
        {% endfor %}   
    </div>

   {% endblock %}
</body>
</html>
 

mysite/pdf/templates/pdf/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>{{user_profile.name}}</h2>
    <h2>Email: {{user_profile.email}}</h2>
    <h2>Mobile: {{user_profile.phone}}</h2>
    <hr/>
    <br/>
    <p>Summary</p>
    <p>{{user_profile.summary}}</p>
    <hr/>
    <p>Skills</p>
    <p>{{user_profile.skills}}</p>
    <hr/>
    <p>Education</p>
    <ul>
        <li>Schooling: {{user_profile.school}}</li>
        <li>{{user_profile.degree}} from {{user_profile.university}}</li>
    </ul>
    <hr/>
    <br/>
    <p>Previous Work Experince</p>
    <p>{{user_profile.previous_work}}</p>
 
</body>
</html>

mysite/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <form method="POST">
                {%csrf_token%}
                    {% for field in form %}
                    <div class="form-group">
                        {{field.name}}
                        {{field}}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-info"> Login </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

</body>
</html>

mysite/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out</title>
</head>
<body>
<h1>You have been logged out </h1>
<a href="{% url 'login'%}" class="btn btn-link"> Login again</a>
</body>
</html>

mysite/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
{% extends 'food/base.html' %}
{% block body %}
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" height="300px" class="card"/>
{% endblock %}
</body>
</html>

mysite/users/templates/users/register.html
{% extends 'food/base.html'%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
{% block body %}
 <div class="container">
     <div class="row">
         <div class="col-md-4 offset-md-4">
             <div class="card">
                 <div class="card-header text-white bg-info">
                     <div class="card-title">
                         Registration
                     </div>
                 </div>
                 <form method="POST">
                 {%csrf_token%}
                 {% for field in form%}
                 <div class="form-group">
                 {{field.name}}
                     <br>
                 {{field}}
                 </div>
                 {% endfor %}
                <button type="submit" class="btn btn-info">Sign Up</button>

                 </form>
             </div>
         </div>
     </div>
 </div>

<
{% endblock %}

</body>
</html>